[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
board_build.f_cpu = 80000000L

lib_deps = 
    m5stack/M5StickCPlus
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    t-vk/ESP32 BLE Keyboard @ ^0.3.2